#!/usr/bin/env bash

if command -v subl >/dev/null 2>&1
then
    git config --global core.editor "subl -w"
elif command -v code >/dev/null 2>&1
then
    git config --global core.editor "code --wait"
fi

if command -v tortoisemerge >/dev/null 2>&1
then
    git config --global diff.tool tortoisediff
    git config --global difftool.prompt false
    git config --global difftool.tortoisediff.cmd "TortoiseMerge -mine \$REMOTE -base \$LOCAL"
    git config --global merge.tool tortoisemerge
    git config --global mergetool.prompt false
    git config --global mergetool.keepBackup false
    git config --global mergetool.tortoisemerge.cmd "TortoiseMerge -base \$BASE -theirs \$REMOTE -mine \$LOCAL -merged \$MERGED"
fi

if command -v powershell >/dev/null 2>&1
then
    mkdir -p ~/Documents/WindowsPowerShell && cp Microsoft.PowerShell_profile.ps1 $_
fi
if command -v pwsh >/dev/null 2>&1
then
    mkdir -p ~/Documents/PowerShell && cp Microsoft.PowerShell_profile.ps1 $_
fi
