#!/bin/sh

# -Z flag to choose-tree has been supported since tmux 2.7
# https://raw.githubusercontent.com/tmux/tmux/2.7/CHANGES
if printf "$(tmux -V | awk '{print $2}')\n2.7\n" | sort -c 2>/dev/null
then
    choose_tree_zoom="choose-tree"
    choose_window_zoom="choose-window"
else
    choose_tree_zoom="choose-tree -Z"
    choose_window_zoom="choose-window -Z"
fi

# Old systems might not recognize "screen-256color"
if infocmp screen-256color >/dev/null 2>&1
then
    set_256_color='set -g default-terminal "screen-256color"'
fi

sed -e "s/%CHOOSE-TREE-ZOOM%/$choose_tree_zoom/g" \
    -e "s/%CHOOSE-WINDOW-ZOOM%/$choose_window_zoom/g" \
    -e "s/%SET-256-COLOR%/$set_256_color/g" \
    "$@" /dev/null
