#!/usr/bin/env node

const inTerminal = [
    {
        type: "frontmost_application_if",
        bundle_identifiers: [
            "^com\\.googlecode\\.iterm2$",
            "^com\\.apple\\.Terminal$"
        ]
    }
];

const macbookRightControlKeyRules = {
    title: "Taemin's configurations",
    rules: [
        {
            description: "Change left shift space to option space",
            manipulators: [
                {
                    type: "basic",
                    from: {
                        key_code: "spacebar",
                        modifiers: {
                            mandatory: ["left_shift"]
                        }
                    },
                    to: {
                        key_code: "spacebar",
                        modifiers: ["right_alt"]
                    }
                }
            ]
        },
        {
            description: "Change left arrow to right control in terminal",
            manipulators: [
                {
                    type: "basic",
                    from: {
                        key_code: "left_arrow",
                        modifiers: {
                            optional: ["any"]
                        }
                    },
                    to: [{key_code: "right_control"}],
                    conditions: inTerminal
                },
                {
                    type: "basic",
                    from: {
                        key_code: "i",
                        modifiers: {
                            mandatory: ["fn"],
                            optional: ["any"]
                        }
                    },
                    to: [{key_code: "up_arrow"}],
                    conditions: inTerminal
                },
                {
                    type: "basic",
                    from: {
                        key_code: "j",
                        modifiers: {
                            mandatory: ["fn"],
                            optional: ["any"]
                        }
                    },
                    to: [{key_code: "left_arrow"}],
                    conditions: inTerminal
                },
                {
                    type: "basic",
                    from: {
                        key_code: "k",
                        modifiers: {
                            mandatory: ["fn"],
                            optional: ["any"]
                        }
                    },
                    to: [{key_code: "down_arrow"}],
                    conditions: inTerminal
                },
                {
                    type: "basic",
                    from: {
                        key_code: "l",
                        modifiers: {
                            mandatory: ["fn"],
                            optional: ["any"]
                        }
                    },
                    to: [{key_code: "right_arrow"}],
                    conditions: inTerminal
                }
            ]
        }
    ]
}

console.log(JSON.stringify(macbookRightControlKeyRules))
