#!/bin/sh

root_dir="$(dirname "$0")"

ruledir="$HOME/.config/karabiner/assets/complex_modifications"
mkdir -p "$ruledir"
sed "s/IS_TERMINAL/[{ \
\"type\": \"frontmost_application_if\", \
\"bundle_identifiers\": \
[\"^com\\\\\\\\.googlecode\\\\\\\\.iterm2\$\", \
\"^com\\\\\\\\.apple\\\\\\\\.Terminal\$\"]}]/" \
    "$root_dir/taemin.json.in" >"$ruledir/taemin.json"

# Make rebase safer on MacOS
# For more details see https://www.git-tower.com/blog/make-git-rebase-safe-on-osx/
git config --global core.trustctime false

echo '

# MacPorts bash-completion
# See https://trac.macports.org/wiki/howto/bash-completion
# To enable git completion, you need to install the MacPorts Git with +bash_completion option
# See https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion#macports
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    . /opt/local/etc/profile.d/bash_completion.sh
fi
' >>~/.bashrc

if ! grep -qE 'auth\s+sufficient\s+pam_tid\.so' /etc/pam.d/sudo
then
    echo "Add 'auth sufficient pam_tid.so' into /etc/pam.d/sudo to enable TouchID for sudo" >&2
fi

if command -v jmacs >/dev/null 2>&1
then
    git config --global core.editor jmacs
fi

if command -v fzf >/dev/null 2>&1
then
    pkgmgr="$(fzf --version | perl -ne 'print lc $1 if /\(([a-zA-Z]*)\)$/')"
    case "$pkgmgr" in
        brew|macports)
            cp -a "$root_dir/fzf-$pkgmgr.bash" ~/.fzf.bash
            cp -a "$root_dir/fzf-$pkgmgr.zsh" ~/.fzf.zsh
            ;;
    esac
else
    rm -rf ~/.fzf.bash ~/.fzf.zsh
fi
