(defun taemin-duplicate-line ()
  (interactive "*")
  (let ((old-point (point)))
    (kill-new (buffer-substring (line-beginning-position) (line-end-position)))
    (end-of-line)
    (open-line 1)
    (forward-char)
    (yank)
    (goto-char old-point)
    (next-line 1)))

(defun taemin-duplicate-last-non-blank ()
  (interactive)
  (let ((old-point (point)))
    (skip-chars-backward " \t\n")
    (if (= (line-beginning-position)
           (line-end-position))
        (progn (goto-char old-point) (error "No line to duplicate"))
      (kill-new (buffer-substring (line-beginning-position) (line-end-position)))
      (goto-char old-point)
      (if (= (line-beginning-position)
              (line-end-position))
          (yank)
        (end-of-line)
        (forward-char 1)
        (open-line 1)
        (yank)))))
