#!/bin/sh

vscode_dir=~/.config/Code/User
mkdir -p "$vscode_dir" && cp vscode/settings.json "$vscode_dir"

if command -v jmacs >/dev/null 2>&1
then
    git config --global core.editor jmacs
fi

touch ~/.hushlogin
